version: '3.7'

volumes:
  app_database: {}
  app_memcached: {}

networks:
  app_net:
    driver: bridge
    name: app_net

services:
  nginx:
    image: nginx:latest
    depends_on:
      - php_app
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ../:/var/www/app
      - ./nginx/symfony-5.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_net

  php_app:
    build: php
    hostname: app_hostname
    volumes:
      - ../:/var/www/app
      - ./data/shell_history:/home/utente/shell_history
    networks:
      - app_net
    environment:
      - HISTFILE=/home/utente/shell_history/.zsh_history

  servicedb:
    image: mariadb:10.5.1
    volumes:
      - app_database:/var/lib/mysql
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      # - MYSQL_USER=app_db_user
      # - MYSQL_PASSWORD=
    networks:
      - app_net
    #command: mysqld --sql_mode="" #Per mysql, non serve per mariadb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - servicedb
    environment:
      - PMA_HOST=servicedb
    networks:
      - app_net

  servicememcached:
    image: memcached:latest
    volumes:
      - app_memcached:/var/lib/memcached
    networks:
      - app_net

  nodejs:
    build: nodejs
    working_dir: /var/www/app
    volumes:
      - ../:/var/www/app
    networks:
      - app_net
